src/pages/api/localisation/index.ts
src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
src/server/localisations/domain/localisation.repository.ts
src/server/localisations/infra/repositories/apiGeoLocalisation.repository.ts
src/server/localisations/useCases/récupérerLocalisationAvecCodeInseeUseCase.ts
src/server/offresEmploi/infra/repositories/apiPoleEmploiOffre.repository.ts
tests/pages/api/localisation/index.test.ts

Premier jet pour la gestion des erreurs de mapping. 
NEXT STEP : avoir ces logs dans le client direct et pas coté répo je m'occuperais de rendre ca plus générique jeudi pro :)
PS : c'est mal mais j'ai pas ajouté de TU comme ce code est voué a finir dans le client et pas dans le répo pour éviter tout le bruit des logs

tech: log erreur mapping réponse toutes les apis

---

src/pages/apprentissage/[id].tsx
src/pages/articles/[id].tsx
src/pages/emplois/[id].tsx
src/pages/jobs-etudiants/[id].tsx
src/server/alternances/infra/repositories/apiLaBonneAlternance.mapper.ts
src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
src/server/alternances/infra/repositories/matchasResponse.type.ts
src/server/localisations/infra/repositories/apiGeoLocalisation.repository.ts
src/server/offresEmploi/infra/repositories/apiPoleEmploiOffre.repository.ts
tests/server/alternances/infra/repositories/apiLaBonneAlternance.repository.test.ts
tests/server/offresEmploi/infra/repositories/apiPoleEmploiOffre.repository.test.ts

Toutes les erreurs étaient dans Sentry <3

fix: erreur mapping get alternance

---

src/client/components/features/Alternance/Rechercher/RechercherAlternance.tsx
src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.module.css
src/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.tsx
src/client/components/features/Engagement/Rechercher/RechercherMission.tsx
src/client/hooks/useMissionEngagementQuery.ts
src/client/services/missionEngagement/missionEngagement.service.ts
src/pages/api/benevolats/index.ts
src/pages/api/services-civique/index.ts
src/server/alternances/domain/alternance.ts
src/server/engagement/domain/engagement.ts
tests/client/components/features/Engagement/FormulaireRecherche/FormulaireRechercheMissionEngagement.test.tsx
tests/client/components/features/Engagement/Rechercher/RechercherMission.test.tsx
tests/client/components/features/OffreEmploi/Rechercher/RechercherOffreEmploi.test.tsx
tests/fixtures/domain/missionEngagement.fixture.ts

feat: rechercher mission engagement avec distance

---

src/pages/index.tsx
src/pages/stages/index.tsx

Ajout d'un lien vers la page des stages sur la page d'accueil
Modification du title de la page de recherche de stages

feat[stages]: modification de la page d'accueil et de stages

---

src/client/components/features/ContratEngagementJeune/FormulaireDeContact/FormulaireDeContact.tsx

fix: linter develop

---

src/client/components/ui/Meilisearch/MeilisearchStats.tsx
src/pages/stages/index.tsx

Ajout d'un component MeilisearchStats pour avoir le nombre de resultats lors d'une recherche d'offres de stage

feat(stage): affichage du nombre d'offres de stage

---

src/pages/stages/index.tsx

feat(stage): affichage des resultats par date de debut de stage descendant

---

src/client/components/features/OffreDeStage/OffreDeStage.type.ts
src/client/components/layouts/RechercherStage/RésultatRechercherStage.tsx
src/pages/stages/index.tsx

feat(stage): retirer la description de la page resultat de recherche de stage

---

sentry.client.config.ts
src/pages/_app.tsx

permet de retirer les trackers en environnement de dev mais aussi de supprimer des warning associés si on les bloque

fix proposal: suppression des tracker en environnement de dev

---

src/client/components/ui/Meilisearch/MeiliSearchCustomPagination.tsx
src/client/components/ui/Meilisearch/tests/MeilsearchCustomPagination.test.tsx
src/client/components/ui/Pagination/CommonPagination.tsx
src/client/components/ui/Pagination/Pagination.tsx
src/pages/stages/index.tsx
tests/client/components/ui/Pagination/Pagination.test.tsx

insane de ouf @LiquidITGuy si tu veux jeter un oeil

refactor: mutalisation de la pagination classique et meilisearch

---

src/client/components/features/OffreDeStage/Consulter/ConsulterOffreDeStage.tsx

feat(Stage): ajout de la description de l'employeur dans le détail d'une offre

---

src/server/services/http/oldClientService.ts
tests/client/useRouter.mock.ts
tests/fixtures/services/httpClientService.fixture.ts

Corriger des types qui sont passés sous les radars avant l'étape de build

fix(dependencies): correction types

---

sentry.client.config.ts

chore(Sentry): changement de la variable d'env

---

public/icons/mail.svg
src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnementDesktop.tsx
src/client/components/features/Accompagnement/Rechercher/RésultatRechercherAccompagnementMobile.tsx
src/client/components/features/ContratEngagementJeune/Accompagnement/Accompagnement.tsx
src/client/components/ui/Icon/Icon.tsx
src/client/components/ui/Icon/angle-down.icon.tsx
src/client/components/ui/Icon/angle-left-from-line.icon.tsx
src/client/components/ui/Icon/angle-left.icon.tsx
src/client/components/ui/Icon/angle-right-from-line.icon.tsx
src/client/components/ui/Icon/angle-right.icon.tsx
src/client/components/ui/Icon/angle-up.icon.tsx
src/client/components/ui/Icon/arrow-right.icon.tsx
src/client/components/ui/Icon/book.icon.tsx
src/client/components/ui/Icon/brief-case.icon.tsx
src/client/components/ui/Icon/burger-menu-left.icon.tsx
src/client/components/ui/Icon/burger-menu.icon.tsx
src/client/components/ui/Icon/close.icon.tsx
src/client/components/ui/Icon/compass.icon.tsx
src/client/components/ui/Icon/error.icon.tsx
src/client/components/ui/Icon/external-redirection.icon.tsx
src/client/components/ui/Icon/filter.icon.tsx
src/client/components/ui/Icon/home.icon.tsx
src/client/components/ui/Icon/information.icon.tsx
src/client/components/ui/Icon/magnifying-glass.icon.tsx
src/client/components/ui/Icon/mail.icon.tsx
src/client/components/ui/Icon/menu.icon.tsx
src/client/components/ui/Icon/svgProps.type.tsx
src/client/components/ui/Icon/trophy.icon.tsx
src/pages/index.page.tsx

TODO : Fix l'erreur avec le svg

fix(accompagnement): ne pas afficher bouton contact si email non renseigné

---

cypress/e2e/formulaire_cej.cy.ts
cypress/e2e/formulaire_entreprise.cy.ts

feat(entreprise/test e2e): ajout de test avec cypress sur le formulaire entreprise

---

cypress/e2e/les-entreprises-s-engagent.cy.ts
src/client/components/features/JeDeviensMentor/RecrutementCandidatPôleEmploi/RecrutementCandidatPôleEmploi.tsx
src/client/components/features/LesEntreprisesSEngagent/Rejoignez/Inscription/Inscription.tsx
src/pages/immersions/index.page.tsx
src/pages/je-recrute-afpr-poei/index.page.tsx

/les-entreprises-s-engagent
/je-recrute-afpr-poei
/immersions

fix(multiple): Fix titres de pages

---

src/client/components/features/FicheMétier/Rechercher/RésultatRechercherMétier.tsx
src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.test.tsx
src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.tsx

https://jira-mcas.atlassian.net/jira/software/c/projects/UNJ1S/boards/55?modal=detail&selectedIssue=UNJ1S-1136&quickFilter=484

fix(multiple): accessibilité titre carte en h3

---

src/client/components/features/Partner/Card/PartnerCard.module.scss
src/client/components/ui/Card/ArticleCard.module.scss
src/client/components/ui/Card/ArticleCard.tsx
src/pages/logements/aides-logement/index.page.tsx

pages : /logements/aides-logement
/espace-jeune

fix(multiple): image déformées articleCard

---

src/pages/_app.page.tsx
src/styles/globals.css

avec un fix global des pages avec trop de contenu

fix(espace-jeune): page trop grande

---

src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétion.module.scss
src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétion.tsx
src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionPays/InputAutocomplétionPays.test.tsx
src/client/components/ui/Form/InputAutocomplétion/InputAutocomplétionPays/InputAutocomplétionPays.tsx
src/client/domain/pays.ts

• Ajout d'un champ d'autocomplétion pour les pays avec la lib react autosuggest

feat(stages): ajout d'un formulaire d'autocomplétion de pays

---

cypress/e2e/formulaire_depot_stage.cy.ts
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffre.fixture.ts
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaire.module.scss
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaireEnvoye.tsx
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaireLocalisation.tsx
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaireStage.test.tsx
src/pages/stages/deposer-offre/confirmation-envoi/DeposerOffreStageEtapeFin.module.scss
src/pages/stages/deposer-offre/confirmation-envoi/index.page.tsx

Pour la review : tout ce que j'ai fait est sur ce commit => [feat(stage): depot de stage page formulaire envoyé](https://github.com/DNUM-SocialGouv/1j1s-front/pull/811/commits/a8dc3ed14fdb951d6e0e62291b91726ada318381)

feat(stage): depot stage formulaire envoyé

---

package-lock.json
package.json
src/client/services/httpClient.service.ts
src/server/services/http/httpClientService.fixture.ts

UNJ1S-1341 passage vers la majeure

chore(dependencies): mise à jour Axios

---

src/pages/api/benevolats/index.controller.ts
src/pages/api/services-civique/index.controller.ts
src/server/configuration/dependencies.container.ts
src/server/engagement/domain/engagement.repository.ts
src/server/engagement/domain/engagement.ts
src/server/engagement/domain/missionEngagement.fixture.ts
src/server/engagement/infra/repositories/apiEngagement.builder.test.ts
src/server/engagement/infra/repositories/apiEngagement.builder.ts
src/server/engagement/infra/repositories/apiEngagement.mapper.ts
src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
src/server/engagement/infra/repositories/apiEngagement.repository.ts
src/server/engagement/infra/repositories/apiEngagement.response.ts
src/server/engagement/useCases/rechercherMissionBenevolat.useCase.ts
src/server/engagement/useCases/rechercherMissionServiceCivique.useCase.ts
src/server/services/utils/urlParams.util.test.ts
src/server/services/utils/urlParams.util.ts

Déplacement de constantes de l'API Engagement (publisher ID) du controller vers le repository

refactor(engagement): déplacement du publisher

---

src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaireEntreprise.test.tsx
src/pages/stages/deposer-offre/Formulaire/StageDeposerOffreFormulaireEntreprise.tsx

UNJ1S-1364-Ajouter-une-r-gle-aux-champs-de-type-url-du-d-p-t-d-offre-de-stage #a-tester

fix(stages): vérification que les URLs sont bien des URLs

---

src/client/components/features/Accompagnement/FormulaireRecherche/FormulaireRechercheAccompagnement.test.tsx
src/client/components/features/Alternance/FormulaireRecherche/FormulaireRechercheAlternance.test.tsx
src/client/components/features/Alternance/FormulaireRecherche/FormulaireRechercheAlternancePE.test.tsx
src/client/components/features/Alternance/Rechercher/RechercherAlternancePoleEmploi.test.tsx
src/client/components/features/Alternance/Rechercher/RechercherAlternancePoleEmploi.tsx
src/client/components/features/Engagement/Rechercher/RechercherMission.test.tsx
src/client/components/features/Engagement/Rechercher/RechercherMission.tsx
src/client/components/features/Formation/FormulaireRecherche/FormulaireRechercherFormation.test.tsx
src/client/components/features/JobÉtudiant/FormulaireRecherche/FormulaireRechercheJobÉtudiant.test.tsx
src/client/components/features/JobÉtudiant/Rechercher/RechercherJobÉtudiant.test.tsx
src/client/components/features/JobÉtudiant/Rechercher/RechercherJobÉtudiant.tsx
src/client/components/features/OffreEmploi/FormulaireRecherche/FormulaireRechercheOffreEmploi.test.tsx
src/client/components/features/OffreEmploi/Rechercher/RechercherOffreEmploi.test.tsx
src/client/components/features/OffreEmploi/Rechercher/RechercherOffreEmploi.tsx
src/client/hooks/useAccompagnementQuery.ts
src/client/hooks/useAlternanceQuery.ts
src/client/hooks/useMissionEngagementQuery.ts
src/client/hooks/useOffreQuery.ts
src/client/services/missionEngagement/missionEngagement.service.test.ts
src/client/services/missionEngagement/missionEngagement.service.ts
src/client/services/offre/offre.service.test.ts
src/client/services/offre/offre.service.ts

Pour :
- les offres Pôle Emploi (alternances quand LBA feature flippé off, emplois et jobs étudiants)
- engagement (service civique et bénévolat)
- alternances LBA (formations et contrats)
- accompagnement.

feat(multiple): filtrer les query params

---

config/headers.js
src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.test.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.tsx
src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.module.scss
src/client/components/features/CampagneApprentissage/VideosCampagneApprentissage/VideosCampagneApprentissage.tsx
src/client/components/ui/Button/button-component.module.scss
src/client/components/ui/Icon/Icon.tsx
src/client/components/ui/Icon/arrow-left.icon.tsx
src/client/components/ui/Icon/play-circle.icon.tsx
src/pages/apprentissage-jeunes/index.page.test.tsx
src/pages/apprentissage-jeunes/index.page.tsx
src/server/cms/configuration/dependencies.container.ts
src/server/cms/domain/cms.repository.ts
src/server/cms/domain/videoCampagneApprentissage.fixture.ts
src/server/cms/domain/videoCampagneApprentissage.type.ts
src/server/cms/infra/repositories/strapi.fixture.ts
src/server/cms/infra/repositories/strapi.mapper.test.ts
src/server/cms/infra/repositories/strapi.mapper.ts
src/server/cms/infra/repositories/strapi.repository.test.ts
src/server/cms/infra/repositories/strapi.repository.ts
src/server/cms/infra/repositories/strapi.response.ts
src/server/cms/useCases/recupererVideosCampagneApprentissage.useCase.ts
src/server/cms/useCases/récupérerVidéosCampagneApprentissage.useCase.ts
src/server/services/logger.service.fixture.ts

TODO : Ajouter les droits video-campagne-apprentissage sur "Public"

feat(alternance): recuperation de video depuis Strapi

---

src/client/components/features/CampagneApprentissage/CampagneApprentissage.module.scss
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/CampagneApprentissageEntreprises.test.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/CampagneApprentissageEntreprises.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/InformationSurEmbaucheApprenti/InformationSurEmbaucheApprenti.module.scss
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/InformationSurEmbaucheApprenti/InformationSurEmbaucheApprenti.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.test.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageJeunes/CampagneApprentissageJeunes.tsx
src/pages/choisir-apprentissage/index.page.test.tsx

+ rewording du titre de pages de campagne

feat(apprentissage): ajouter section vous envisagez de recruter un apprenti

---

terraform/cdn.tf
terraform/locals.tf

Correspond à la tâche JIRA : https://jira-mcas.atlassian.net/browse/UNJ1S-1383

chore: activation de Cloudflare sur la recette

---

docs/docs/adr/2023-05-23.format-adr.md
docs/docs/adr/2023-05-23.ne-pas-utiliser-as-unknown-as-myclass.md
docs/docs/adr/ADR.md

- ADR sur le format des ADR
- ADR sur les casts `as unknwon as MyClass`

docs: Ajoute des ADR

---

src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.module.scss
src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.test.tsx
src/client/components/features/FormationInitiale/ConsulterDetail/ConsulterDetailFormationInitiale.tsx
src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.test.tsx
src/client/components/features/FormationInitiale/Rechercher/RechercherFormationInitiale.tsx
src/pages/formations-initiales/[id].page.test.tsx
src/pages/formations-initiales/[id].page.tsx
src/server/formations-initiales/domain/formationInitiale.fixture.ts
src/server/formations-initiales/domain/formationInitiale.ts
src/server/formations-initiales/infra/formationInitiale.mapper.test.ts
src/server/formations-initiales/infra/formationInitiale.mapper.ts
src/server/formations-initiales/infra/formationInitialeResponse.fixture.ts
src/server/formations-initiales/infra/onisepFormationInitiale.repository.ts

feat(formations init): récupération du détail part 2

---

.github/workflows/terraform-template.yml

fix(ci): revert terraform to 1.5.7 because of hashicorp/terraform#33983

---

src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.test.ts
src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.ts
src/server/offres/infra/repositories/pole-emploi/poleEmploiOffre.response.fixture.ts
src/server/offres/infra/repositories/pole-emploi/poleEmploiOffre.response.ts

This reverts commit 300231be849fa95761808357b390033aef5893fe.

fix(emplois): Revert "feat(offre): validation api pole emploi (#1901)"

---

docs/package-lock.json
docs/package.json

This reverts commit 68d0ca24b7a65a69e0bf1f0b1c637d189aad1ac7.

Revert "fix(deps): update dependency @mdx-js/react to v3 (#2211)"

---

src/client/components/features/EmploisEurope/FormulaireRecherche/FormulaireRechercheEmploisEurope.module.scss
src/client/components/features/EmploisEurope/FormulaireRecherche/FormulaireRechercheEmploisEurope.test.tsx
src/client/components/features/EmploisEurope/FormulaireRecherche/FormulaireRechercheEmploisEurope.tsx
src/client/components/features/EmploisEurope/Rechercher/RechercherEmploisEurope.test.tsx
src/client/components/features/EmploisEurope/Rechercher/RechercherEmploisEurope.tsx
src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.test.tsx
src/client/domain/typesContratEures.ts
src/client/hooks/useEmploiEuropeQuery.ts
src/pages/api/emplois-europe/index.controller.test.ts
src/pages/api/emplois-europe/index.controller.ts
src/server/emplois-europe/domain/emploiEurope.ts
src/server/emplois-europe/infra/repositories/apiEuresEmploiEurope.fixture.ts
src/server/emplois-europe/infra/repositories/apiEuresEmploiEurope.repository.test.ts
src/server/emplois-europe/infra/repositories/apiEuresEmploiEurope.repository.ts

NOTE : Regarder juste le dernier commit pour la review

feat(europe): recherche emplois par type de contrat

---

src/client/components/features/Alternance/Rechercher/FormulaireRecherche/FormulaireRechercheAlternance.test.tsx
src/client/components/features/Alternance/Rechercher/FormulaireRecherche/FormulaireRechercheAlternance.tsx
src/client/components/features/Alternance/Rechercher/RechercherAlternance.test.tsx
src/client/components/ui/Form/Combobox/ComboboxCommune/ComboboxCommune.test.tsx
src/client/components/ui/Form/Combobox/ComboboxCommune/ComboboxCommune.tsx
src/client/components/ui/Form/Combobox/Option.tsx
src/client/utils/recupererLibelleDepuisValeur.utils.test.ts
src/client/utils/recupererLibelleDepuisValeur.utils.ts
src/server/localisations/domain/localisationAvecCoordonnées.fixture.ts

- Contient uniquement l'implem et l'ajout dans la recherche d'alternance

feat(UI): mise en place du combobox commune

---

src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.test.tsx
src/client/components/features/Stages3eme/FormulaireRecherche/ListeResultatsStage3eme.tsx
src/client/components/features/Stages3eme/Rechercher/RechercherStages3eme.test.tsx
src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.tsx
src/server/stage-3eme/domain/stage3eme.fixture.ts
src/server/stage-3eme/domain/stage3eme.ts
src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.fixture.ts
src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.mapper.test.ts
src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.mapper.ts
src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.repository.test.ts
src/server/stage-3eme/infra/repositories/apiImmersionFacileStage3eme.ts

Pour la PR : Regarder que le dernier commit j'ai du rebase sur la branche de https://github.com/DNUM-SocialGouv/1j1s-front/pull/2350

feat(stage3eme): ajouter tag carte résultats

---

src/client/components/ui/Select/Select.test.tsx
src/client/components/ui/Select/Select.tsx
src/pages/les-entreprises-s-engagent/inscription/index.page.test.tsx
src/pages/les-entreprises-s-engagent/inscription/index.page.tsx

Les énormes diff des fichiers viennent du reformattage (indent, espace etc)
Sur les deux fichiers qui ont une gross diff j'ai fait ressortir les seuls endroits auxquels j'ai apporté une modif par rapport à la version précédente

fix(select): permettre de prendre en compte la selection d'une option quand elle se fait au clavier

---

src/client/components/ui/Form/Combobox/ComboboxCommune/ComboboxCommune.test.tsx
src/client/components/ui/Form/Combobox/ComboboxCommune/ComboboxCommune.tsx

fix(combobox): combobox commune lancer la recherche à partir de 3 caractères

---

src/client/hooks/usePageHistory.test.tsx
src/client/hooks/usePageHistory.ts

Affiche le back button même lorsque Next tourne en SPA

fix: Fix le BackButton sur le build

---

src/client/components/layouts/Footer/Footer.test.tsx
src/client/components/layouts/Footer/Footer.tsx

Mise à jour du logo textuel 
Mise à jour des tests liés au logo

feat(accueil): modifier le logo du ministere

---

docs/docs/onboarding/1-installation.md
src/client/components/features/CampagneApprentissage/CampagneApprentissage.module.scss
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/CampagneApprentissageEntreprises.test.tsx
src/client/components/features/CampagneApprentissage/CampagneApprentissageEntreprises/CampagneApprentissageEntreprises.tsx

L'image et la couleur de fond du hero pourront être modifiées si les éléments nous parviennent.

feat(campagne): modifie le hero de presentation apprentissage employeur
