DNUM-SocialGouv/1j1s-front

- src/pages/apprentissage/[id].tsx
- src/pages/articles/[id].tsx
- src/pages/emplois/[id].tsx
- src/pages/jobs-etudiants/[id].tsx
J'ai testé ça : [https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta) mais ça marche pas tip top moumoute (c'est seulement en beta il parle de sortir des optims +lts à la version 13 de next) par contre je pense que c'est la solution cible donc j'ai noté cette solution dans le board tech :)
Sinon pour tester en mode TU c'était pas possible (par contre j'ai trouvé une lib de test de page directement et pas que de composant [https://www.npmjs.com/package/next-page-tester](https://www.npmjs.com/package/next-page-tester) mais ces salows sont encore en react 17...) mais ce que j'ai fait c'est que j'ai collé un compteur …
> feat: ajout d'un unvalidate cache quand une ressource n'a pas été trouvé

- src/pages/mesures-employeurs/index.tsx
utilisation du <BoutonRetour /> qui va chercher dans le stockage local de session la page précédente.
> [671]:  Bouton retour depuis les mesures employeurs

- src/server/alternances/infra/repositories/apiPoleEmploiAlternance.repository.ts
- src/server/demande-de-contact/infra/strapiDemandeDeContact.repository.ts
- src/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.ts
- src/server/entreprises/infra/strapiRejoindreLaMobilisation.repository.ts
- src/server/jobs-étudiants/infra/repositories/apiPoleEmploiJobÉtudiant.repository.ts
- src/server/offres/infra/repositories/pole-emploi/apiPoleEmploiError.ts
- src/server/offres/infra/repositories/pole-emploi/apiPoleEmploiRéférentiel.repository.ts
- src/server/services/http/httpClientService.ts
- src/server/services/http/httpClientWithAuthentification.service.ts
- tests/fixtures/services/poleEmploiHttpClientService.fixture.ts
- tests/fixtures/services/strapiHttpClientService.fixture.ts
- tests/pages/api/alternances/index.test.ts
- tests/server/alternances/infra/repositories/apiPoleEmploiAlternance.repository.test.ts
- tests/server/emplois/infra/repositories/apiPoleEmploiOffre.repository.test.ts
- tests/server/emplois/infra/repositories/apiPoleEmploiRéférentiel.repository.test.ts
- tests/server/entreprises/infra/strapiRejoindreLaMobilisation.repository.test.ts
- tests/server/jobs-étudiants/infra/repositories/apiPoleEmploiJobÉtudiant.repository.test.ts
- tests/server/offres/infra/repositories/pole-emploi/apiPoleEmploiError.test.ts
- tests/server/services/http/httpClientWithAuthentification.service.test.ts
- tsconfig.json
J'ai géré le non logging de :
- les 204 sur le get
- les 204 sur la recherche
- les 400 avec les formats de message d'erreur qu'on connait (pour les gérer plus tard coté front)
Vous voyez d'autre cas à pas logger ?
Sinon tout le reste on log !
> feat(pole emploi): gestion des erreurs

- CONTRIBUTING.md
- src/pages/decouvrir-les-metiers/[id].tsx
Note : même fix que pour https://github.com/DNUM-SocialGouv/1j1s-front/commit/372cdb30ae7efde3da7d47b59110e5e052186b6d
> fix(decouvrir-les-metiers): correction bouton retour dans la page détail d'un metier

- .github/workflows/run-e2e-test.yml
Permettra de ne plus utiliser les github secrets 🙌
> ci(e2e): use .env.test as .env in e2e action

- public/google7e90d409f9a92608.html
le changement dns n'ayant pas été totalement effectué, la vérification pour le google webmastering tool a lieu via le fichier
> chore(google): ajout du fichier d'identification google

- config/headers.js
Ceci vise à corriger le problème remonté par Pole Emploi pour la page "/emplois/deposer-offre":
> Bonjour,
> l’erreur étant :
> Refused to frame 'https://www.1jeune1solution.gouv.fr/maintenance-pole-emploi' because it violates the following Content Security Policy directive: "frame-src *.apprentissage.beta.gouv.fr immersion-facile.beta.gouv.fr deposer-offre.www.1jeune1solution.gouv.fr *.youtube.com".
> Et de ce que je vois des échanges réseau, la CSP en cause est celle-ci (dans laquelle il manquerait donc  www.1jeune1solution.gouv.fr) :
> content-security-policy:  […] frame-src *.apprentissage.beta.gouv.fr immersion-facile.beta.gouv.fr deposer-offre.www.1jeune1solution.gouv.fr *.youtube.com;
> Cette CSP est portée par la page https://www.1jeune1solution.gouv.fr/emplois/deposer-offre et …
> fix: ajouter self parmi la liste des iframes autorisées par les CSP

- src/pages/api/etablissements-accompagnement/index.controller.test.ts
- src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.test.ts
- src/server/alternances/infra/repositories/apiLaBonneAlternance.repository.ts
- src/server/alternances/infra/repositories/apiLaBonneAlternanceError.ts
- src/server/cms/infra/repositories/strapi.error.ts
- src/server/cms/infra/repositories/strapi.repository.test.ts
- src/server/engagement/infra/repositories/apiEngagement.repository.test.ts
- src/server/engagement/infra/repositories/apiEngagementError.ts
- src/server/entreprises/infra/apiRejoindreLaMobilisationError.ts
- src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.test.ts
- src/server/formations/infra/repositories/apiLaBonneAlternanceFormation.repository.ts
- src/server/formations/infra/repositories/apiLaBonneAlternanceFormationError.ts
- src/server/formations/infra/repositories/apiTrajectoiresProStatistique.repository.test.ts
- src/server/formations/infra/repositories/apiTrajectoiresProStatistique.repository.ts
- src/server/formations/infra/repositories/apiTrajectoiresProStatistiqueError.ts
- src/server/localisations/infra/repositories/apiAdresse.error.ts
- src/server/localisations/infra/repositories/apiAdresse.repository.test.ts
- src/server/localisations/infra/repositories/apiGeo.error.ts
- src/server/mail/infra/repositories/tipimail.repository.test.ts
- src/server/mail/infra/repositories/tipimail.repository.ts
- src/server/metiers/infra/apiLaBonneAlternanceMétier.repository.test.ts
- src/server/offres/infra/repositories/pole-emploi/apiPoleEmploiError.test.ts
- src/server/offres/infra/repositories/pole-emploi/apiPoleEmploiError.ts
- src/server/services/http/cachedHttpClient.service.ts
- src/server/services/http/httpError.fixture.ts
- src/server/services/http/httpError.ts
- src/server/services/http/publicHttpClient.service.ts
- src/server/établissement-accompagnement/infra/apiÉtablissementPublic.repository.test.ts
- src/server/établissement-accompagnement/infra/apiÉtablissementPublic.repository.ts
Correction sur ce que je disais au daily : des erreurs sont aussi déclenché lorsque la page est affiché en mode dégradé (ex : les statistiques ne sont pas trouvé)
👉 Est ce qu'il faudrait passer en log de niveau warn pour créer moins de bruit sur Sentry ?
> fix(multiple): gestion erreur Sentry Api LBA et Trajectories Pro

- .github/workflows/lighthouse.yml
- .github/workflows/run-build.yml
- .github/workflows/run-e2e-test.yml
- .github/workflows/run-lint-and-unit-test.yml
Cette PR active le cache pour `npm` (c'est à dire le dossier `node_modules`) afin d'accélérer les Github Actions.
Cela doit permettre également de faire moins de requêtes vers le registry npm et d'autres sources de packages et de binaires et d'éviter les erreurs de quota comme celle-ci: https://github.com/DNUM-SocialGouv/1j1s-front/actions/runs/5066896242/jobs/9097261698?pr=1354
> ci: active le cache des node_modules pour accélerer les Github Actions

- terraform/front.tf
pour des raisons contractuelles entre les ministères et Scalingo. Il nous est désormais interdit d'utiliser des addons qui n'ont pas de SLA, y compris pour les environnement hors-prod.
Résoud une tâche JIRA pas encore créée ^^
> chore(terraform): upgrade de redis en recette vers redis-starter-256

- src/client/components/features/OffreDeStage/Consulter/ConsulterOffreDeStage.test.tsx
- src/client/components/features/OffreDeStage/Consulter/ConsulterOffreDeStage.tsx
- src/client/components/features/OffreDeStage/OffreDeStage.test.tsx
- src/client/components/features/OffreDeStage/OffreDeStage.tsx
- src/client/components/features/OffreDeStage/offreDeStageIndexee.fixture.ts
- src/server/cms/domain/offreDeStage.fixture.ts
- src/server/cms/domain/offreDeStage.type.ts
- src/server/cms/infra/repositories/strapi.fixture.ts
- src/server/cms/infra/repositories/strapi.mapper.test.ts
- src/server/cms/infra/repositories/strapi.mapper.ts
- src/server/cms/infra/repositories/strapi.response.ts
Wording modifié sur la carte d'offre de stage et sur la page détail d'une offre de stage
Des tests (en plus des tests sur la date de début min/max) ont été ajouté pour bien vérifier les quelques logiques dans le composant qui n'étaient pas testées.
Le ménage sur l'utilisation de la `dateDeDebut` a été commencé : sur toute la partie affichage d'une offre de stage, il ne devrait plus y avoir d'utilisation de `dateDeDebut`.
Par contre, le ménage reste à faire sur la partie dépôt de stage par un employeur 
⚠️ MEP : cela implique de mettre en prod le CMS avant le front
> feat(stage): mettre a jour le wording sur la page de detail dun stage

- .github/renovate.json
- .github/workflows/run-build.yml
- .github/workflows/run-e2e-test.yml
- .github/workflows/run-lint-and-unit-test.yml
- activer les workflows de test sur la création de branche, 
- activer l’option automerge=true + automergeType=branch pour que Renovate puisse merger la branche sans passer par une PR (a nécessité l'activation de l’option `Allow specified actors to bypass required pull requests → renovate bot` dans Branch protection rules de main)
- Si les tests passent, la branche est bien mergée sans intervention humaine, sinon renovate créer une PR.
> chore(renovate): activer auto merge de branche de mise à jour de patch

- src/client/components/features/OffreDeStage/Consulter/ConsulterOffreDeStage.tsx
- src/client/components/layouts/RechercherSolution/Résultat/RésultatRechercherSolution.tsx
- src/client/components/ui/Tag/TagList.stories.tsx
- src/client/components/ui/Tag/TagList.test.tsx
- src/client/components/ui/Tag/TagList.tsx
Passage directement à ReactNode (car on en aura besoin pour l'US qui demande d'ajouter un lien téléphonique dans les resultats des structures d'accompagnement)
> chore: changer le type de TagList pour Array<ReactNode>

- src/server/formations-initiales/infra/formationInitialeResponse.fixture.ts
- src/server/formations-initiales/infra/onisepFormationInitiale.repository.ts
Objet de cette PR : supprimer les champs inutiles dans notre contexte de l'api onisep pour les formations initiales
> chore(form-init): suppression des champs non utilisés de l’objet API

- src/server/services-jeunes/domain/servicesJeunes.fixture.ts
- src/server/services-jeunes/domain/servicesJeunes.ts
- src/server/services-jeunes/infra/strapiServicesJeunes.mapper.test.ts
- src/server/services-jeunes/infra/strapiServicesJeunes.mapper.ts
Aujourd'hui, le type ServiceJeune embarque plus de choses que ce qui lui est nécessaire pour l'affichage de la carte ServiceJeune. 
Cette PR a pour but de supprimer ces champs du mapper pour simplifier le type et le traitement
> chore(service-jeune): suppression des champs non utilisés

- src/client/components/features/MesuresEmployeurs/MesuresEmployeurs.tsx
- src/server/mesures-employeurs/domain/mesureEmployeur.fixture.ts
- src/server/mesures-employeurs/domain/mesureEmployeur.ts
- src/server/mesures-employeurs/infra/strapiMesuresEmployeurs.mapper.test.ts
- src/server/mesures-employeurs/infra/strapiMesuresEmployeurs.mapper.ts
- src/server/mesures-employeurs/infra/strapiMesuresEmployeurs.repository.test.ts
Aujourd'hui, le type MesureEmployeur embarque plus de choses que ce qui lui est nécessaire pour l'affichage de la carte MesureEmployeur.
Cette PR a pour but de supprimer ces champs du mapper pour simplifier le type et le traitement
> chore(mesure-employeur): suppression des champs non utilisés

- src/client/components/features/ContratEngagementJeune/FormulaireContactCEJ/FormulaireContactCEJ.test.tsx
- src/client/components/features/ContratEngagementJeune/FormulaireContactCEJ/FormulaireContactCEJ.tsx
- src/client/components/features/OffreDeStage/Déposer/Étape1Entreprise/StageDeposerOffreFormulaireÉtape1Entreprise.test.tsx
- src/client/components/features/OffreDeStage/Déposer/Étape1Entreprise/StageDeposerOffreFormulaireÉtape1Entreprise.tsx
- src/pages/les-entreprises-s-engagent/inscription/index.page.test.tsx
- src/pages/les-entreprises-s-engagent/inscription/index.page.tsx
Formulaires en question : 
- contact CEJ 
- Les entreprises s'engagent 
- Depot d'offre de stage (nom entreprise + email, pas le reste des champs)
Voir à la revue s'il faut inclure email pro ou pas pour LEE et depot stage
> feat(formulaires): a11y ajouter les attributs autocomplete sur les formulaires quand c'est pertinent

- terraform/front.tf
La sortie d'Ubuntu 24.04 étant proche, c'est le moment d'upgrade à mon avis. Aucun impact attendu puisque Node 20 est bien compatible avec Ubuntu 22.
> chore: upgrade to Ubuntu 22 on Scalingo

- docker-compose.yml
Reverts DNUM-SocialGouv/1j1s-front#2884
La version dispo dans le cloud est 1.7.4, pas 1.7.5
> Revert "chore(deps): update getmeili/meilisearch docker tag to v1.7.6"

- next.config.js
Exemple d'un build en local qui se poursuit malgré l'erreur (et qui la log).
> ci: build même avec Sentry en erreur

- src/client/components/features/ServicesJeunes/ServicesJeunes.tsx
- src/pages/espace-jeune/index.page.test.tsx
- src/pages/services-jeunes/index.analytics.ts
- src/pages/services-jeunes/index.module.scss
- src/pages/services-jeunes/index.page.test.tsx
- src/pages/services-jeunes/index.page.tsx
Création d'une nouvelle page `services-jeunes` plutôt que reprise de l'ancienne page `espace-jeune` avec
redirection
> feat(services-jeunes): crée la page simple

- src/client/components/ui/Checkbox/Checkbox.module.scss
- src/client/components/ui/Radio/Radio.module.scss
avant : 
après : 
Autre option :
> fix: Fix l'alignement des radios et checkboxes

- src/pages/index.page.test.tsx
- src/pages/index.page.tsx
Modification de la bannière à réaliser pour le 31/10
> feat(campagne): modification banniere apprentis
